### ISSUE TITLE
Osadzanie ścieżek do folderów w kodzie

### ISSUE THREAD

**Issue by stasulam** [stasulam/mieszkai#1]
@OlafSk https://github.com/stasulam/mieszkai/blob/a3abcb22735a9a060a2bb79a9fd1db7e61cf3bba/visualizations/mapy.R#L5

Zastanawiałem się nad tym, jak można rozwiązać ten problem. W przypadku `R` pomocne będzie utworzenie projektu `.Rproj` w głównym katalogu projektu. Wówczas, niezależnie od platformy i użytkownika, będzie możliwe proste odwoływanie się do katalogów projektu (np. `crawlers/crawlers/flats.jl`).

W przypadku skyptów `.py` sugeruję tworzenie shell scriptów do wykonywania prostych operacji, z których korzystamy. On w defaulcie za katalog początkowy będzie traktował ten, w którym został zapisany (zob. `to_csv.py` z głównego katalogu projektu).

**Comment by OlafSk** [comment]
Zrobiłem projekt .Rproj w folderze i działa, więc to podejście będzie chyba najlepsze, co do skryptów R.
